# Generated by Django 6.1.1 on 2026-09-12 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('games', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.CharField(max_length=100)),
                ('trigger_type', models.CharField(choices=[('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled'), ('BULK', 'Bulk')], max_length=20)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.environmentconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='GameTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('url_check_status', models.CharField(default='NOT_TESTED', max_length=20)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('page_load_status', models.CharField(default='NOT_TESTED', max_length=20)),
                ('launch_status', models.CharField(default='NOT_TESTED', max_length=20)),
                ('game_screen_status', models.CharField(default='NOT_TESTED', max_length=20)),
                ('loading_status', models.CharField(default='NOT_TESTED', max_length=20)),
                ('console_status', models.CharField(default='NOT_TESTED', max_length=20)),
                ('network_status', models.CharField(default='NOT_TESTED', max_length=20)),
                ('ocr_status', models.CharField(default='NOT_TESTED', max_length=20)),
                ('expected_text_status', models.CharField(default='NOT_TESTED', max_length=20)),
                ('page_load_time_ms', models.IntegerField(blank=True, null=True)),
                ('launch_time_ms', models.IntegerField(blank=True, null=True)),
                ('screenshot_time_ms', models.IntegerField(blank=True, null=True)),
                ('screenshot_url', models.URLField(blank=True, null=True)),
                ('screenshot_path', models.CharField(blank=True, max_length=500, null=True)),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('console_errors', models.JSONField(blank=True, default=list)),
                ('network_errors', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('final_status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('WARNING', 'Warning'), ('NOT_TESTED', 'Not Tested')], default='NOT_TESTED', max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='games.game')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitoring.testrun')),
            ],
        ),
    ]
