# Generated by Django 6.1.1 on 2026-09-12 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('game_url', models.URLField(blank=True, help_text='Direct URL to the game if available', null=True)),
                ('launch_url', models.URLField(blank=True, help_text='URL to trigger the game launch (e.g. from lobby)', null=True)),
                ('expected_text', models.CharField(blank=True, help_text='Primary expected text to match in OCR', max_length=255)),
                ('expected_text_list', models.JSONField(blank=True, default=list, help_text='List of alternate expected texts')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='providers.provider')),
            ],
        ),
        migrations.CreateModel(
            name='GameConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_timeout_seconds', models.IntegerField(default=30)),
                ('screenshot_delay_seconds', models.IntegerField(default=5)),
                ('max_loading_seconds', models.IntegerField(default=60)),
                ('expected_text', models.CharField(blank=True, max_length=255)),
                ('expected_error_texts', models.JSONField(blank=True, default=list, help_text='List of error texts to fail on')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='games.game')),
            ],
        ),
    ]
